/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ARM 1
#undef  CONFIG_EISA
#undef  CONFIG_SBUS
#undef  CONFIG_MCA
#define CONFIG_UID16 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#undef  CONFIG_GENERIC_BUST_SPINLOCK
#undef  CONFIG_GENERIC_ISA_DMA

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#undef  CONFIG_OBSOLETE

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#define CONFIG_KMOD 1

/*
 * System Type
 */
#undef  CONFIG_ARCH_ANAKIN
#undef  CONFIG_ARCH_ARCA5K
#undef  CONFIG_ARCH_CLPS7500
#undef  CONFIG_ARCH_CLPS711X
#undef  CONFIG_ARCH_CO285
#define CONFIG_ARCH_PXA 1
#undef  CONFIG_ARCH_EBSA110
#undef  CONFIG_ARCH_CAMELOT
#undef  CONFIG_ARCH_FOOTBRIDGE
#undef  CONFIG_ARCH_INTEGRATOR
#undef  CONFIG_ARCH_S3C2410
#undef  CONFIG_ARCH_OMAHA
#undef  CONFIG_ARCH_L7200
#undef  CONFIG_ARCH_MX1ADS
#undef  CONFIG_ARCH_RPC
#undef  CONFIG_ARCH_RISCSTATION
#undef  CONFIG_ARCH_SA1100
#undef  CONFIG_ARCH_SHARK
#undef  CONFIG_ARCH_AT91RM9200DK
#undef  CONFIG_MINIMAL_OOPS

/*
 * Linux As Bootldr support
 */
#undef  CONFIG_LAB
#undef  CONFIG_BIG_KERNEL
#undef  CONFIG_USE_DATE_CODE

/*
 * Archimedes/A5000 Implementations
 */

/*
 * Archimedes/A5000 Implementations (select only ONE)
 */
#undef  CONFIG_ARCH_ARC
#undef  CONFIG_ARCH_A5K

/*
 * Footbridge Implementations
 */
#undef  CONFIG_ARCH_CATS
#undef  CONFIG_ARCH_PERSONAL_SERVER
#undef  CONFIG_ARCH_EBSA285_ADDIN
#undef  CONFIG_ARCH_EBSA285_HOST
#undef  CONFIG_ARCH_NETWINDER

/*
 * SA11x0 Implementations
 */
#undef  CONFIG_SA1100_ACCELENT
#undef  CONFIG_SA1100_ASSABET
#undef  CONFIG_ASSABET_NEPONSET
#undef  CONFIG_SA1100_ADSBITSY
#undef  CONFIG_SA1100_BRUTUS
#undef  CONFIG_SA1100_CEP
#undef  CONFIG_SA1100_CERF
#undef  CONFIG_SA1100_H3100
#undef  CONFIG_SA1100_H3600
#undef  CONFIG_SA1100_H3800
#undef  CONFIG_SA1100_CONSUS
#undef  CONFIG_SA1100_EXTENEX1
#undef  CONFIG_SA1100_FLEXANET
#undef  CONFIG_SA1100_FREEBIRD
#undef  CONFIG_SA1100_FRODO
#undef  CONFIG_SA1100_GRAPHICSCLIENT
#undef  CONFIG_SA1100_GRAPHICSMASTER
#undef  CONFIG_SA1100_HACKKIT
#undef  CONFIG_SA1100_BADGE4
#undef  CONFIG_SA1100_JORNADA720
#undef  CONFIG_SA1100_JORNADA56X
#undef  CONFIG_SA1100_HUW_WEBPANEL
#undef  CONFIG_SA1100_ITSY
#undef  CONFIG_SA1100_LART
#undef  CONFIG_SA1100_NANOENGINE
#undef  CONFIG_SA1100_OMNIMETER
#undef  CONFIG_SA1100_PANGOLIN
#undef  CONFIG_SA1100_PLEB
#undef  CONFIG_SA1100_PT_SYSTEM3
#undef  CONFIG_SA1100_SHANNON
#undef  CONFIG_SA1100_SHERMAN
#undef  CONFIG_SA1100_SIMPAD
#undef  CONFIG_SA1100_SIMPUTER
#undef  CONFIG_SA1100_PFS168
#undef  CONFIG_SA1100_VICTOR
#undef  CONFIG_SA1100_XP860
#undef  CONFIG_SA1100_YOPY
#undef  CONFIG_SA1100_USB
#undef  CONFIG_SA1100_USB_NETLINK
#undef  CONFIG_SA1100_USB_CHAR
#undef  CONFIG_REGISTERS

/*
 * Intel PXA250/210 Implementations
 */
#undef  CONFIG_ARCH_LUBBOCK
#undef  CONFIG_ARCH_PXA_IDP
#undef  CONFIG_ARCH_PXA_CERF
#define CONFIG_ARCH_H3900 1
#define CONFIG_ARCH_H1900 1
#define CONFIG_ARCH_H5400 1
#undef  CONFIG_ARCH_H2200
#define CONFIG_ARCH_AXIM 1
#undef  CONFIG_PXA_USB
#define CONFIG_PXA_USB_MODULE 1
#undef  CONFIG_PXA_USB_NETLINK
#define CONFIG_PXA_USB_NETLINK_MODULE 1
#undef  CONFIG_PXA_USB_CHAR
#define CONFIG_PXA_USB_CHAR_MODULE 1

/*
 * CLPS711X/EP721X Implementations
 */
#undef  CONFIG_ARCH_AUTCPU12
#undef  CONFIG_ARCH_CDB89712
#undef  CONFIG_ARCH_CLEP7312
#undef  CONFIG_ARCH_EDB7211
#undef  CONFIG_ARCH_P720T
#undef  CONFIG_ARCH_FORTUNET
#undef  CONFIG_ARCH_EP7211
#undef  CONFIG_ARCH_EP7212
#undef  CONFIG_ARCH_ACORN
#undef  CONFIG_FOOTBRIDGE
#undef  CONFIG_FOOTBRIDGE_HOST
#undef  CONFIG_FOOTBRIDGE_ADDIN

/*
 * Processor Type
 */
#define CONFIG_CPU_32 1
#undef  CONFIG_CPU_26
#undef  CONFIG_CPU_ARM610
#undef  CONFIG_CPU_ARM710
#undef  CONFIG_CPU_ARM720T
#undef  CONFIG_CPU_ARM920T
#undef  CONFIG_CPU_ARM922T
#undef  CONFIG_PLD
#undef  CONFIG_CPU_ARM926T
#undef  CONFIG_CPU_ARM1020
#undef  CONFIG_CPU_ARM1026
#undef  CONFIG_CPU_SA110
#undef  CONFIG_CPU_SA1100
#define CONFIG_CPU_32v5 1
#define CONFIG_CPU_XSCALE 1
#define CONFIG_XSCALE_CACHE_ERRATA 1
#undef  CONFIG_CPU_32v3
#undef  CONFIG_CPU_32v4
#undef  CONFIG_SA1100_IPAQ
#define CONFIG_PXA_IPAQ 1
#define CONFIG_IPAQ_HANDHELD 1

/*
 * Compaq iPAQ Handheld
 */
#undef  CONFIG_IPAQ_HAL
#define CONFIG_IPAQ_HAL_MODULE 1
#undef  CONFIG_H3600_MICRO
#define CONFIG_IPAQ_HAS_ROSELLA 1
#undef  CONFIG_H3600_ASIC
#define CONFIG_H3600_ASIC_MODULE 1
#undef  CONFIG_H3900_ASIC_DEBUG
#define CONFIG_H3900_ASIC_DEBUG_MODULE 1
#undef  CONFIG_H5400_ASIC
#define CONFIG_H5400_ASIC_MODULE 1
#undef  CONFIG_H1900_ASIC
#define CONFIG_H1900_ASIC_MODULE 1
#undef  CONFIG_H1900_TS
#define CONFIG_H1900_TS_MODULE 1
#undef  CONFIG_H3600_HARDWARE
#define CONFIG_H3600_HARDWARE_MODULE 1
#undef  CONFIG_IPAQ_SLEEVE
#define CONFIG_IPAQ_SLEEVE_MODULE 1
#define CONFIG_SLEEVE_DEBUG 1
#define CONFIG_SLEEVE_DEBUG_VERBOSE (0)

/*
 * Dell Axim X5
 */
#undef  CONFIG_AXIM_HAL
#define CONFIG_AXIM_HAL_MODULE 1

/*
 * Processor Features
 */
#undef  CONFIG_DISCONTIGMEM

/*
 * General setup
 */
#undef  CONFIG_PCI
#undef  CONFIG_ISA
#undef  CONFIG_ISA_DMA
#undef  CONFIG_ZBOOT_ROM
#define CONFIG_ZBOOT_ROM_TEXT 0x0
#define CONFIG_ZBOOT_ROM_BSS 0x0
#define CONFIG_CPU_FREQ 1
#define CONFIG_HOTPLUG 1

/*
 * PCMCIA/CardBus support
 */
#undef  CONFIG_PCMCIA
#define CONFIG_PCMCIA_MODULE 1
#undef  CONFIG_I82092
#undef  CONFIG_I82365
#undef  CONFIG_TCIC
#undef  CONFIG_PCMCIA_CLPS6700
#undef  CONFIG_PCMCIA_SA1100
#undef  CONFIG_PCMCIA_PXA
#define CONFIG_PCMCIA_PXA_MODULE 1
#undef  CONFIG_MERCURY_BACKPAQ

/*
 * MMC/SD Card support
 */
#undef  CONFIG_MMC
#define CONFIG_MMC_MODULE 1
#define CONFIG_MMC_DEBUG 1
#define CONFIG_MMC_DEBUG_VERBOSE (0)
#undef  CONFIG_MMC_SAMSUNG_ASIC
#define CONFIG_MMC_SAMSUNG_ASIC_MODULE 1
#undef  CONFIG_MMC_S3C2410
#undef  CONFIG_MMC_H5400
#define CONFIG_MMC_H5400_MODULE 1
#define CONFIG_NET 1
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef  CONFIG_XIP_KERNEL

/*
 * At least one math emulation must be selected
 */
#define CONFIG_FPE_NWFPE 1
#undef  CONFIG_FPE_FASTFPE
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_MISC
#define CONFIG_PM 1
#undef  CONFIG_APM
#define CONFIG_APM_MODULE 1
#undef  CONFIG_HWTIMER
#undef  CONFIG_ARTHUR
#define CONFIG_CMDLINE "keepinitrd"
#define CONFIG_ALIGNMENT_TRAP 1

/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT
#define CONFIG_PARPORT_MODULE 1
#undef  CONFIG_PARPORT_PC
#define CONFIG_PARPORT_PC_MODULE 1
#undef  CONFIG_PARPORT_PC_CML1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#undef  CONFIG_PARPORT_SERIAL
#undef  CONFIG_PARPORT_PC_FIFO
#undef  CONFIG_PARPORT_PC_SUPERIO
#undef  CONFIG_PARPORT_PC_PCMCIA
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef  CONFIG_PARPORT_ARC
#undef  CONFIG_PARPORT_IDP
#undef  CONFIG_PARPORT_AMIGA
#undef  CONFIG_PARPORT_MFC3
#undef  CONFIG_PARPORT_ATARI
#undef  CONFIG_PARPORT_GSC
#undef  CONFIG_PARPORT_SUNBPP
#undef  CONFIG_PARPORT_OTHER
#undef  CONFIG_PARPORT_1284

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#define CONFIG_MTD_DEBUG 1
#define CONFIG_MTD_DEBUG_VERBOSE (1)
#define CONFIG_MTD_PARTITIONS 1
#undef  CONFIG_MTD_CONCAT
#undef  CONFIG_MTD_REDBOOT_PARTS
#define CONFIG_MTD_CMDLINE_PARTS 1
#undef  CONFIG_MTD_AFS_PARTS

/*
 * User Modules And Translation Layers
 */
#undef  CONFIG_MTD_CHAR
#define CONFIG_MTD_CHAR_MODULE 1
#define CONFIG_MTD_BLOCK 1
#undef  CONFIG_FTL
#undef  CONFIG_NFTL
#undef  CONFIG_INFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#undef  CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef  CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef  CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef  CONFIG_MTD_CFI_B1
#define CONFIG_MTD_CFI_B2 1
#define CONFIG_MTD_CFI_B4 1
#undef  CONFIG_MTD_CFI_B8
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef  CONFIG_MTD_CFI_I4
#undef  CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT 1
#undef  CONFIG_MTD_CFI_AMDSTD
#undef  CONFIG_MTD_CFI_STAA
#undef  CONFIG_MTD_RAM
#undef  CONFIG_MTD_ROM
#undef  CONFIG_MTD_ABSENT
#undef  CONFIG_MTD_OBSOLETE_CHIPS
#undef  CONFIG_MTD_AMDSTD
#undef  CONFIG_MTD_SHARP
#undef  CONFIG_MTD_JEDEC

/*
 * Mapping drivers for chip access
 */
#undef  CONFIG_MTD_COMPLEX_MAPPINGS
#undef  CONFIG_MTD_PHYSMAP
#define CONFIG_MTD_IPAQ 1
#undef  CONFIG_MTD_ARM_INTEGRATOR
#undef  CONFIG_MTD_CDB89712
#undef  CONFIG_MTD_SA1100
#undef  CONFIG_MTD_DC21285
#undef  CONFIG_MTD_IQ80310
#undef  CONFIG_MTD_LUBBOCK
#undef  CONFIG_MTD_EPXA10DB
#undef  CONFIG_MTD_FORTUNET
#undef  CONFIG_MTD_AUTCPU12
#undef  CONFIG_MTD_EDB7312
#undef  CONFIG_MTD_H720X
#undef  CONFIG_MTD_IMPA7
#undef  CONFIG_MTD_CEIVA
#undef  CONFIG_MTD_PCI
#undef  CONFIG_MTD_PCMCIA

/*
 * Self-contained MTD device drivers
 */
#undef  CONFIG_MTD_PMC551
#undef  CONFIG_MTD_SLRAM
#undef  CONFIG_MTD_MTDRAM
#undef  CONFIG_MTD_BLKMTD
#define CONFIG_MTD_BLKMTD_MODULE 1

/*
 * Disk-On-Chip Device Drivers
 */
#undef  CONFIG_MTD_DOC2000
#undef  CONFIG_MTD_DOC2001
#undef  CONFIG_MTD_DOC2001PLUS
#undef  CONFIG_MTD_DOCPROBE

/*
 * NAND Flash Device Drivers
 */
#undef  CONFIG_MTD_NAND

/*
 * Plug and Play configuration
 */
#undef  CONFIG_PNP
#undef  CONFIG_ISAPNP

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_CISS_SCSI_TAPE
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_UMEM
#undef  CONFIG_BLK_DEV_LOOP
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#undef  CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_SIZE (4096)
#define CONFIG_BLK_DEV_INITRD 1
#undef  CONFIG_NVRD
#define CONFIG_NVRD_MODULE 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#undef  CONFIG_BLK_DEV_MD
#undef  CONFIG_MD_LINEAR
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_MD_MULTIPATH
#undef  CONFIG_BLK_DEV_LVM
#define CONFIG_BLK_DEV_LVM_MODULE 1
#undef  CONFIG_BLK_DEV_DM
#define CONFIG_BLK_DEV_DM_MODULE 1

/*
 * Networking options
 */
#undef  CONFIG_PACKET
#define CONFIG_PACKET_MODULE 1
#define CONFIG_PACKET_MMAP 1
#undef  CONFIG_NETLINK_DEV
#define CONFIG_NETFILTER 1
#undef  CONFIG_NETFILTER_DEBUG
#define CONFIG_FILTER 1
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef  CONFIG_IP_ADVANCED_ROUTER
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#define CONFIG_NET_IPIP_MODULE 1
#undef  CONFIG_NET_IPGRE
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#undef  CONFIG_IP_MROUTE
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES

/*
 *   IP: Netfilter Configuration
 */
#undef  CONFIG_IP_NF_CONNTRACK
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#undef  CONFIG_IP_NF_FTP
#define CONFIG_IP_NF_FTP_MODULE 1
#undef  CONFIG_IP_NF_IRC
#define CONFIG_IP_NF_IRC_MODULE 1
#undef  CONFIG_IP_NF_QUEUE
#undef  CONFIG_IP_NF_IPTABLES
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LIMIT
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MAC
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MARK
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#undef  CONFIG_IP_NF_MATCH_MULTIPORT
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TOS
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_AH_ESP
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#undef  CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TTL
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef  CONFIG_IP_NF_MATCH_TCPMSS
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#undef  CONFIG_IP_NF_MATCH_STATE
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#undef  CONFIG_IP_NF_MATCH_UNCLEAN
#undef  CONFIG_IP_NF_MATCH_OWNER
#undef  CONFIG_IP_NF_FILTER
#define CONFIG_IP_NF_FILTER_MODULE 1
#undef  CONFIG_IP_NF_TARGET_REJECT
#undef  CONFIG_IP_NF_TARGET_MIRROR
#undef  CONFIG_IP_NF_NAT
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#undef  CONFIG_IP_NF_TARGET_MASQUERADE
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#undef  CONFIG_IP_NF_TARGET_REDIRECT
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#undef  CONFIG_IP_NF_NAT_LOCAL
#undef  CONFIG_IP_NF_NAT_SNMP_BASIC
#undef  CONFIG_IP_NF_NAT_IRC
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#undef  CONFIG_IP_NF_NAT_FTP
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#undef  CONFIG_IP_NF_MANGLE
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef  CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#undef  CONFIG_IP_NF_TARGET_MARK
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#undef  CONFIG_IP_NF_TARGET_LOG
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP_NF_TARGET_ULOG
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#undef  CONFIG_IP_NF_TARGET_TCPMSS
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#undef  CONFIG_IP_NF_ARPTABLES
#undef  CONFIG_IP_NF_COMPAT_IPCHAINS
#define CONFIG_IP_NF_COMPAT_IPCHAINS_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#undef  CONFIG_IP_NF_COMPAT_IPFWADM
#undef  CONFIG_IPV6
#define CONFIG_IPV6_MODULE 1
#define CONFIG_IPV6_SUBTREES 1
#undef  CONFIG_IPV6_IPV6_TUNNEL
#define CONFIG_IPV6_IPV6_TUNNEL_MODULE 1
#undef  CONFIG_IPV6_MOBILITY
#define CONFIG_IPV6_MOBILITY_MODULE 1
#define CONFIG_IPV6_MOBILITY_MN 1
#define CONFIG_IPV6_MOBILITY_DEBUG 1

/*
 *   IPv6: Netfilter Configuration
 */
#undef  CONFIG_IP6_NF_QUEUE
#undef  CONFIG_IP6_NF_IPTABLES
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_LIMIT
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MAC
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_MULTIPORT
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_OWNER
#undef  CONFIG_IP6_NF_MATCH_MARK
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#undef  CONFIG_IP6_NF_MATCH_LENGTH
#undef  CONFIG_IP6_NF_MATCH_EUI64
#undef  CONFIG_IP6_NF_FILTER
#define CONFIG_IP6_NF_FILTER_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_LOG
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#undef  CONFIG_IP6_NF_MANGLE
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#undef  CONFIG_IP6_NF_TARGET_MARK
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#undef  CONFIG_KHTTPD
#undef  CONFIG_ATM
#undef  CONFIG_VLAN_8021Q

/*
 *  
 */
#undef  CONFIG_IPX
#undef  CONFIG_ATALK

/*
 * Appletalk devices
 */
#undef  CONFIG_DEV_APPLETALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#define CONFIG_BRIDGE_MODULE 1
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * Network testing
 */
#undef  CONFIG_NET_PKTGEN
#undef  CONFIG_IPSEC
#define CONFIG_IPSEC_MODULE 1

/*
 * IPSec options (FreeS/WAN)
 */
#define CONFIG_IPSEC_IPIP 1
#define CONFIG_IPSEC_AH 1
#define CONFIG_IPSEC_AUTH_HMAC_MD5 1
#define CONFIG_IPSEC_AUTH_HMAC_SHA1 1
#define CONFIG_IPSEC_ESP 1
#define CONFIG_IPSEC_ENC_3DES 1
#undef  CONFIG_IPSEC_IPCOMP
#define CONFIG_IPSEC_DEBUG 1

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#undef  CONFIG_TUN
#define CONFIG_TUN_MODULE 1
#undef  CONFIG_ETHERTAP

/*
 * Ethernet (10 or 100Mbit)
 */
#undef  CONFIG_NET_ETHERNET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_SK98LIN
#undef  CONFIG_TIGON3
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#undef  CONFIG_PPP_ASYNC
#define CONFIG_PPP_ASYNC_MODULE 1
#undef  CONFIG_PPP_SYNC_TTY
#undef  CONFIG_PPP_DEFLATE
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef  CONFIG_PPP_BSDCOMP
#define CONFIG_PPP_BSDCOMP_MODULE 1
#undef  CONFIG_PPPOE
#undef  CONFIG_SLIP

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1
#undef  CONFIG_STRIP
#undef  CONFIG_WAVELAN
#undef  CONFIG_ARLAN
#undef  CONFIG_AIRONET4500
#undef  CONFIG_AIRONET4500_NONCS
#undef  CONFIG_AIRONET4500_PROC
#undef  CONFIG_HERMES
#define CONFIG_HERMES_MODULE 1
#undef  CONFIG_SPECTRUM24T
#define CONFIG_SPECTRUM24T_MODULE 1

/*
 * Wireless Pcmcia cards support
 */
#undef  CONFIG_PCMCIA_HERMES
#define CONFIG_PCMCIA_HERMES_MODULE 1
#undef  CONFIG_AIRO_CS
#define CONFIG_AIRO_CS_MODULE 1
#undef  CONFIG_WVLAN_CS
#define CONFIG_WVLAN_CS_MODULE 1
#undef  CONFIG_MWVLAN_CS
#define CONFIG_MWVLAN_CS_MODULE 1
#undef  CONFIG_HOSTAP
#define CONFIG_HOSTAP_MODULE 1
#undef  CONFIG_HOSTAP_CS
#define CONFIG_HOSTAP_CS_MODULE 1
#define CONFIG_NET_WIRELESS 1

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#undef  CONFIG_PCMCIA_3C589
#define CONFIG_PCMCIA_3C589_MODULE 1
#undef  CONFIG_PCMCIA_3C574
#define CONFIG_PCMCIA_3C574_MODULE 1
#undef  CONFIG_PCMCIA_FMVJ18X
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#undef  CONFIG_PCMCIA_PCNET
#define CONFIG_PCMCIA_PCNET_MODULE 1
#undef  CONFIG_PCMCIA_AXNET
#define CONFIG_PCMCIA_AXNET_MODULE 1
#undef  CONFIG_PCMCIA_NMCLAN
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#undef  CONFIG_PCMCIA_SMC91C92
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#undef  CONFIG_PCMCIA_XIRC2PS
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#undef  CONFIG_ARCNET_COM20020_CS
#undef  CONFIG_PCMCIA_IBMTR
#define CONFIG_NET_PCMCIA_RADIO 1
#undef  CONFIG_PCMCIA_RAYCS
#define CONFIG_PCMCIA_RAYCS_MODULE 1
#undef  CONFIG_PCMCIA_NETWAVE
#define CONFIG_PCMCIA_NETWAVE_MODULE 1
#undef  CONFIG_PCMCIA_WAVELAN
#define CONFIG_PCMCIA_WAVELAN_MODULE 1
#undef  CONFIG_AIRONET4500_CS

/*
 * Amateur Radio support
 */
#undef  CONFIG_HAMRADIO

/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#undef  CONFIG_IRLAN
#define CONFIG_IRLAN_MODULE 1
#undef  CONFIG_IRNET
#define CONFIG_IRNET_MODULE 1
#undef  CONFIG_IRCOMM
#define CONFIG_IRCOMM_MODULE 1
#define CONFIG_IRDA_ULTRA 1

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#define CONFIG_IRDA_DEBUG 1

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#undef  CONFIG_IRTTY_SIR
#define CONFIG_IRTTY_SIR_MODULE 1
#undef  CONFIG_IRPORT_SIR
#define CONFIG_IRPORT_SIR_MODULE 1

/*
 * Dongle support
 */
#undef  CONFIG_DONGLE

/*
 * FIR device drivers
 */
#undef  CONFIG_USB_IRDA
#undef  CONFIG_NSC_FIR
#undef  CONFIG_WINBOND_FIR
#undef  CONFIG_TOSHIBA_FIR
#undef  CONFIG_SMC_IRCC_FIR
#undef  CONFIG_ALI_FIR
#undef  CONFIG_VLSI_FIR
#undef  CONFIG_PXA_FIR
#define CONFIG_PXA_FIR_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef  CONFIG_IDE
#define CONFIG_IDE_MODULE 1

/*
 * IDE, ATA and ATAPI Block devices
 */
#undef  CONFIG_BLK_DEV_IDE
#define CONFIG_BLK_DEV_IDE_MODULE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#undef  CONFIG_BLK_DEV_IDEDISK
#define CONFIG_BLK_DEV_IDEDISK_MODULE 1
#undef  CONFIG_IDEDISK_MULTI_MODE
#undef  CONFIG_IDEDISK_STROKE
#undef  CONFIG_BLK_DEV_IDEDISK_VENDOR
#undef  CONFIG_BLK_DEV_IDEDISK_FUJITSU
#undef  CONFIG_BLK_DEV_IDEDISK_IBM
#undef  CONFIG_BLK_DEV_IDEDISK_MAXTOR
#undef  CONFIG_BLK_DEV_IDEDISK_QUANTUM
#undef  CONFIG_BLK_DEV_IDEDISK_SEAGATE
#undef  CONFIG_BLK_DEV_IDEDISK_WD
#undef  CONFIG_BLK_DEV_COMMERIAL
#undef  CONFIG_BLK_DEV_TIVO
#undef  CONFIG_BLK_DEV_IDECS
#define CONFIG_BLK_DEV_IDECS_MODULE 1
#undef  CONFIG_BLK_DEV_IDECD
#define CONFIG_BLK_DEV_IDECD_MODULE 1
#undef  CONFIG_BLK_DEV_IDETAPE
#define CONFIG_BLK_DEV_IDETAPE_MODULE 1
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#define CONFIG_BLK_DEV_IDEFLOPPY_MODULE 1
#undef  CONFIG_BLK_DEV_IDESCSI
#undef  CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#undef  CONFIG_BLK_DEV_CMD640
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#undef  CONFIG_BLK_DEV_ISAPNP
#undef  CONFIG_IDE_CHIPSETS
#undef  CONFIG_IDEDMA_AUTO
#undef  CONFIG_DMA_NONPCI
#undef  CONFIG_BLK_DEV_IDE_MODES
#undef  CONFIG_BLK_DEV_ATARAID
#undef  CONFIG_BLK_DEV_ATARAID_PDC
#undef  CONFIG_BLK_DEV_ATARAID_HPT

/*
 * SCSI support
 */
#undef  CONFIG_SCSI
#define CONFIG_SCSI_MODULE 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#undef  CONFIG_BLK_DEV_SD
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_SD_EXTRA_DEVS (40)
#undef  CONFIG_CHR_DEV_ST
#undef  CONFIG_CHR_DEV_OSST
#undef  CONFIG_BLK_DEV_SR
#define CONFIG_BLK_DEV_SR_MODULE 1
#undef  CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_SR_EXTRA_DEVS (2)
#undef  CONFIG_CHR_DEV_SG
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef  CONFIG_SCSI_DEBUG_QUEUES
#undef  CONFIG_SCSI_MULTI_LUN
#undef  CONFIG_SCSI_CONSTANTS
#undef  CONFIG_SCSI_LOGGING

/*
 * SCSI low-level drivers
 */
#undef  CONFIG_SCSI_7000FASST
#undef  CONFIG_SCSI_ACARD
#undef  CONFIG_SCSI_AHA152X
#undef  CONFIG_SCSI_AHA1542
#undef  CONFIG_SCSI_AHA1740
#undef  CONFIG_SCSI_AACRAID
#undef  CONFIG_SCSI_AIC7XXX
#undef  CONFIG_SCSI_AIC7XXX_OLD
#undef  CONFIG_SCSI_DPT_I2O
#undef  CONFIG_SCSI_ADVANSYS
#undef  CONFIG_SCSI_IN2000
#undef  CONFIG_SCSI_AM53C974
#undef  CONFIG_SCSI_MEGARAID
#undef  CONFIG_SCSI_BUSLOGIC
#undef  CONFIG_SCSI_DMX3191D
#undef  CONFIG_SCSI_DTC3280
#undef  CONFIG_SCSI_EATA
#undef  CONFIG_SCSI_EATA_DMA
#undef  CONFIG_SCSI_EATA_PIO
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#undef  CONFIG_SCSI_GDTH
#undef  CONFIG_SCSI_GENERIC_NCR5380
#undef  CONFIG_SCSI_INITIO
#undef  CONFIG_SCSI_INIA100
#undef  CONFIG_SCSI_PPA
#undef  CONFIG_SCSI_IMM
#undef  CONFIG_SCSI_NCR53C406A
#undef  CONFIG_SCSI_NCR53C7xx
#undef  CONFIG_SCSI_PAS16
#undef  CONFIG_SCSI_PCI2000
#undef  CONFIG_SCSI_PCI2220I
#undef  CONFIG_SCSI_PSI240I
#undef  CONFIG_SCSI_QLOGIC_FAS
#undef  CONFIG_SCSI_SIM710
#undef  CONFIG_SCSI_SYM53C416
#undef  CONFIG_SCSI_T128
#undef  CONFIG_SCSI_U14_34F
#undef  CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#define CONFIG_SCSI_PCMCIA 1
#undef  CONFIG_PCMCIA_AHA152X
#undef  CONFIG_PCMCIA_FDOMAIN
#undef  CONFIG_PCMCIA_NINJA_SCSI
#undef  CONFIG_PCMCIA_QLOGIC

/*
 * I2O device support
 */
#undef  CONFIG_I2O
#undef  CONFIG_I2O_BLOCK
#undef  CONFIG_I2O_LAN
#undef  CONFIG_I2O_SCSI
#undef  CONFIG_I2O_PROC

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN

/*
 * Input core support
 */
#undef  CONFIG_INPUT
#define CONFIG_INPUT_MODULE 1
#undef  CONFIG_INPUT_KEYBDEV
#define CONFIG_INPUT_KEYBDEV_MODULE 1
#undef  CONFIG_INPUT_MOUSEDEV
#define CONFIG_INPUT_MOUSEDEV_MODULE 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X (1024)
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y (768)
#undef  CONFIG_INPUT_JOYDEV
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef  CONFIG_INPUT_EVDEV
#define CONFIG_INPUT_EVDEV_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_SERIAL 1
#define CONFIG_SERIAL_CONSOLE 1
#define CONFIG_SERIAL_EXTENDED 1
#undef  CONFIG_SERIAL_MANY_PORTS
#undef  CONFIG_SERIAL_SHARE_IRQ
#undef  CONFIG_SERIAL_DETECT_IRQ
#undef  CONFIG_SERIAL_MULTIPORT
#undef  CONFIG_HUB6
#undef  CONFIG_SERIAL_NONSTANDARD

/*
 * Serial drivers
 */
#undef  CONFIG_SERIAL_ANAKIN
#undef  CONFIG_SERIAL_ANAKIN_CONSOLE
#undef  CONFIG_SERIAL_S3C2410
#undef  CONFIG_SERIAL_S3C2410_CONSOLE
#undef  CONFIG_SERIAL_AMBA
#undef  CONFIG_SERIAL_AMBA_CONSOLE
#undef  CONFIG_SERIAL_CLPS711X
#undef  CONFIG_SERIAL_CLPS711X_CONSOLE
#undef  CONFIG_SERIAL_21285
#undef  CONFIG_SERIAL_21285_OLD
#undef  CONFIG_SERIAL_21285_CONSOLE
#undef  CONFIG_SERIAL_UART00
#undef  CONFIG_SERIAL_UART00_CONSOLE
#undef  CONFIG_SERIAL_SA1100
#undef  CONFIG_SERIAL_SA1100_CONSOLE
#undef  CONFIG_SERIAL_8250
#undef  CONFIG_SERIAL_8250_CONSOLE
#undef  CONFIG_SERIAL_8250_EXTENDED
#undef  CONFIG_SERIAL_8250_MANY_PORTS
#undef  CONFIG_SERIAL_8250_SHARE_IRQ
#undef  CONFIG_SERIAL_8250_DETECT_IRQ
#undef  CONFIG_SERIAL_8250_MULTIPORT
#undef  CONFIG_SERIAL_8250_HUB6
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (32)
#undef  CONFIG_PRINTER
#undef  CONFIG_PPDEV
#undef  CONFIG_NEWTONKBD
#define CONFIG_NEWTONKBD_MODULE 1
#undef  CONFIG_SA1100_PROFILER

/*
 * Compaq iPAQ H3600 support
 */
#undef  CONFIG_TOUCHSCREEN_H3600
#define CONFIG_TOUCHSCREEN_H3600_MODULE 1
#undef  CONFIG_H3600_BACKPAQ_FPGA
#undef  CONFIG_H3600_BACKPAQ_ACCEL
#undef  CONFIG_H3600_BACKPAQ_GASGAUGE
#undef  CONFIG_H3600_BACKPAQ_SRAM
#undef  CONFIG_H3600_BACKPAQ_AUDIO
#undef  CONFIG_H3600_STOWAWAY
#undef  CONFIG_H3800_MICROKBD
#undef  CONFIG_SA1100_LIRC
#undef  CONFIG_H5400_BUZZER
#define CONFIG_H5400_BUZZER_MODULE 1

/*
 * I2C support
 */
#undef  CONFIG_I2C
#define CONFIG_I2C_MODULE 1
#undef  CONFIG_I2C_ALGOBIT
#undef  CONFIG_I2C_ALGOPCF
#undef  CONFIG_I2C_PXA_ALGO
#define CONFIG_I2C_PXA_ALGO_MODULE 1
#undef  CONFIG_I2C_PXA_ADAP
#define CONFIG_I2C_PXA_ADAP_MODULE 1
#undef  CONFIG_I2C_CHARDEV
#define CONFIG_I2C_CHARDEV_MODULE 1
#undef  CONFIG_I2C_PROC
#define CONFIG_I2C_PROC_MODULE 1
#undef  CONFIG_I2C_DS1307

/*
 * L3 serial bus support
 */
#undef  CONFIG_L3
#undef  CONFIG_L3_ALGOBIT
#undef  CONFIG_L3_BIT_SA1100_GPIO

/*
 * Other L3 adapters
 */
#undef  CONFIG_L3_S3C2410
#undef  CONFIG_L3_SA1111
#undef  CONFIG_L3_BACKPAQ
#undef  CONFIG_BIT_SA1100_GPIO

/*
 * SPI support
 */
#undef  CONFIG_SPI

/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#undef  CONFIG_MOUSE
#define CONFIG_MOUSE_MODULE 1
#undef  CONFIG_PSMOUSE
#undef  CONFIG_82C710_MOUSE
#undef  CONFIG_PC110_PAD
#undef  CONFIG_MK712_MOUSE

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_GAMEPORT
#undef  CONFIG_INPUT_NS558
#undef  CONFIG_INPUT_LIGHTNING
#undef  CONFIG_INPUT_PCIGAME
#undef  CONFIG_INPUT_CS461X
#undef  CONFIG_INPUT_EMU10K1
#undef  CONFIG_INPUT_SERIO
#define CONFIG_INPUT_SERIO_MODULE 1
#undef  CONFIG_INPUT_SERPORT
#define CONFIG_INPUT_SERPORT_MODULE 1

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_ANALOG
#undef  CONFIG_INPUT_A3D
#undef  CONFIG_INPUT_ADI
#undef  CONFIG_INPUT_COBRA
#undef  CONFIG_INPUT_GF2K
#undef  CONFIG_INPUT_GRIP
#undef  CONFIG_INPUT_INTERACT
#undef  CONFIG_INPUT_TMDC
#undef  CONFIG_INPUT_SIDEWINDER
#undef  CONFIG_INPUT_IFORCE_USB
#undef  CONFIG_INPUT_IFORCE_232
#undef  CONFIG_INPUT_WARRIOR
#undef  CONFIG_INPUT_MAGELLAN
#undef  CONFIG_INPUT_SPACEORB
#undef  CONFIG_INPUT_SPACEBALL
#undef  CONFIG_INPUT_STINGER
#undef  CONFIG_INPUT_DB9
#undef  CONFIG_INPUT_GAMECON
#undef  CONFIG_INPUT_TURBOGRAFX
#undef  CONFIG_QIC02_TAPE

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef  CONFIG_WATCHDOG_NOWAYOUT
#undef  CONFIG_ACQUIRE_WDT
#undef  CONFIG_ADVANTECH_WDT
#undef  CONFIG_ALIM7101_WDT
#undef  CONFIG_SC520_WDT
#undef  CONFIG_PCWATCHDOG
#undef  CONFIG_21285_WATCHDOG
#undef  CONFIG_977_WATCHDOG
#undef  CONFIG_SA1100_WATCHDOG
#undef  CONFIG_PXA_WATCHDOG
#define CONFIG_PXA_WATCHDOG_MODULE 1
#undef  CONFIG_OMAHA_WATCHDOG
#undef  CONFIG_EUROTECH_WDT
#undef  CONFIG_IB700_WDT
#undef  CONFIG_WAFER_WDT
#undef  CONFIG_I810_TCO
#undef  CONFIG_MIXCOMWD
#undef  CONFIG_60XX_WDT
#undef  CONFIG_SC1200_WDT
#undef  CONFIG_SOFT_WATCHDOG
#undef  CONFIG_W83877F_WDT
#undef  CONFIG_WDT
#undef  CONFIG_WDTPCI
#undef  CONFIG_MACHZ_WDT
#undef  CONFIG_NVRAM
#undef  CONFIG_RTC
#undef  CONFIG_PXA_RTC
#define CONFIG_PXA_RTC_MODULE 1
#define CONFIG_PXA_RTC_HACK 1
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#undef  CONFIG_AGP
#undef  CONFIG_DRM

/*
 * PCMCIA character devices
 */
#undef  CONFIG_PCMCIA_SERIAL_CS
#define CONFIG_PCMCIA_SERIAL_CS_MODULE 1
#undef  CONFIG_AXIM_TS
#define CONFIG_AXIM_TS_MODULE 1
#undef  CONFIG_AXIM_KEY
#define CONFIG_AXIM_KEY_MODULE 1
#undef  CONFIG_AXIM_KEY_FIX

/*
 * Multimedia devices
 */
#undef  CONFIG_MEDIA
#define CONFIG_MEDIA_MODULE 1
#undef  CONFIG_VIDEO_DEV
#define CONFIG_VIDEO_DEV_MODULE 1
#undef  CONFIG_V4L2_DEV
#define CONFIG_V4L2_DEV_MODULE 1

/*
 * Video For Linux
 */
#define CONFIG_VIDEO_PROC_FS 1
#undef  CONFIG_I2C_PARPORT

/*
 * Video Adapters
 */
#undef  CONFIG_VIDEO_PMS
#undef  CONFIG_VIDEO_BWQCAM
#undef  CONFIG_VIDEO_CQCAM
#undef  CONFIG_VIDEO_CPIA
#define CONFIG_VIDEO_CPIA_MODULE 1
#undef  CONFIG_VIDEO_CPIA_USB
#define CONFIG_VIDEO_CPIA_USB_MODULE 1
#undef  CONFIG_VIDEO_SAA5249
#undef  CONFIG_TUNER_3036
#undef  CONFIG_VIDEO_STRADIS
#undef  CONFIG_VIDEO_ZORAN
#undef  CONFIG_VIDEO_ZORAN_BUZ
#undef  CONFIG_VIDEO_ZORAN_DC10
#undef  CONFIG_VIDEO_ZORAN_LML33
#undef  CONFIG_VIDEO_ZR36120
#undef  CONFIG_VIDEO_MEYE
#undef  CONFIG_VIDEO_CYBERPRO
#undef  CONFIG_VIDEO_H3600_BACKPAQ
#undef  CONFIG_VIDEO_HAWKEYE

/*
 * Video for Linux 2 (V4L2)
 */
#undef  CONFIG_VIDEO_WINNOV_CS
#define CONFIG_VIDEO_WINNOV_CS_MODULE 1

/*
 * Radio Adapters
 */
#undef  CONFIG_RADIO_CADET
#undef  CONFIG_RADIO_RTRACK
#undef  CONFIG_RADIO_RTRACK2
#undef  CONFIG_RADIO_AZTECH
#undef  CONFIG_RADIO_GEMTEK
#undef  CONFIG_RADIO_GEMTEK_PCI
#undef  CONFIG_RADIO_MAXIRADIO
#undef  CONFIG_RADIO_MAESTRO
#undef  CONFIG_RADIO_MIROPCM20
#undef  CONFIG_RADIO_MIROPCM20_RDS
#undef  CONFIG_RADIO_SF16FMI
#undef  CONFIG_RADIO_TERRATEC
#undef  CONFIG_RADIO_TRUST
#undef  CONFIG_RADIO_TYPHOON
#undef  CONFIG_RADIO_ZOLTRIX

/*
 * File systems
 */
#undef  CONFIG_QUOTA
#undef  CONFIG_AUTOFS_FS
#undef  CONFIG_AUTOFS4_FS
#define CONFIG_AUTOFS4_FS_MODULE 1
#undef  CONFIG_REISERFS_FS
#define CONFIG_REISERFS_FS_MODULE 1
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_REISERFS_PROC_INFO
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_BFS_FS
#undef  CONFIG_EXT3_FS
#define CONFIG_EXT3_FS_MODULE 1
#undef  CONFIG_JBD
#define CONFIG_JBD_MODULE 1
#undef  CONFIG_JBD_DEBUG
#undef  CONFIG_FAT_FS
#define CONFIG_FAT_FS_MODULE 1
#undef  CONFIG_MSDOS_FS
#define CONFIG_MSDOS_FS_MODULE 1
#undef  CONFIG_UMSDOS_FS
#define CONFIG_UMSDOS_FS_MODULE 1
#undef  CONFIG_VFAT_FS
#define CONFIG_VFAT_FS_MODULE 1
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG (0)
#undef  CONFIG_JFFS2_FS_NAND
#define CONFIG_CRAMFS 1
#define CONFIG_TMPFS 1
#define CONFIG_RAMFS 1
#undef  CONFIG_ISO9660_FS
#define CONFIG_ISO9660_FS_MODULE 1
#undef  CONFIG_JOLIET
#undef  CONFIG_ZISOFS
#undef  CONFIG_MINIX_FS
#undef  CONFIG_VXFS_FS
#undef  CONFIG_NTFS_FS
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_PROC_FS 1
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#undef  CONFIG_DEVFS_DEBUG
#undef  CONFIG_DRIVERFS_FS
#define CONFIG_DEVPTS_FS 1
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#undef  CONFIG_EXT2_FS
#define CONFIG_EXT2_FS_MODULE 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_INTERMEZZO_FS
#undef  CONFIG_NFS_FS
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef  CONFIG_ROOT_NFS
#undef  CONFIG_NFSD
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#undef  CONFIG_SUNRPC
#define CONFIG_SUNRPC_MODULE 1
#undef  CONFIG_LOCKD
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#undef  CONFIG_SMB_FS
#define CONFIG_SMB_FS_MODULE 1
#undef  CONFIG_SMB_NLS_DEFAULT
#undef  CONFIG_NCP_FS
#undef  CONFIG_NCPFS_PACKET_SIGNING
#undef  CONFIG_NCPFS_IOCTL_LOCKING
#undef  CONFIG_NCPFS_STRONG
#undef  CONFIG_NCPFS_NFS_NS
#undef  CONFIG_NCPFS_OS2_NS
#undef  CONFIG_NCPFS_SMALLDOS
#undef  CONFIG_NCPFS_NLS
#undef  CONFIG_NCPFS_EXTRAS
#undef  CONFIG_ZISOFS_FS

/*
 * Partition Types
 */
#undef  CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_SMB_NLS 1
#define CONFIG_NLS 1

/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef  CONFIG_NLS_CODEPAGE_437
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_737
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_775
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_850
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_852
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_855
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_857
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_860
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_861
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_862
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_863
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_864
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_865
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_866
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_869
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_936
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_950
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_932
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_949
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_874
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#undef  CONFIG_NLS_ISO8859_8
#define CONFIG_NLS_ISO8859_8_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_1250
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_1251
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#undef  CONFIG_NLS_ISO8859_1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef  CONFIG_NLS_ISO8859_2
#define CONFIG_NLS_ISO8859_2_MODULE 1
#undef  CONFIG_NLS_ISO8859_3
#define CONFIG_NLS_ISO8859_3_MODULE 1
#undef  CONFIG_NLS_ISO8859_4
#define CONFIG_NLS_ISO8859_4_MODULE 1
#undef  CONFIG_NLS_ISO8859_5
#define CONFIG_NLS_ISO8859_5_MODULE 1
#undef  CONFIG_NLS_ISO8859_6
#define CONFIG_NLS_ISO8859_6_MODULE 1
#undef  CONFIG_NLS_ISO8859_7
#define CONFIG_NLS_ISO8859_7_MODULE 1
#undef  CONFIG_NLS_ISO8859_9
#define CONFIG_NLS_ISO8859_9_MODULE 1
#undef  CONFIG_NLS_ISO8859_13
#define CONFIG_NLS_ISO8859_13_MODULE 1
#undef  CONFIG_NLS_ISO8859_14
#define CONFIG_NLS_ISO8859_14_MODULE 1
#undef  CONFIG_NLS_ISO8859_15
#define CONFIG_NLS_ISO8859_15_MODULE 1
#undef  CONFIG_NLS_KOI8_R
#define CONFIG_NLS_KOI8_R_MODULE 1
#undef  CONFIG_NLS_KOI8_U
#define CONFIG_NLS_KOI8_U_MODULE 1
#undef  CONFIG_NLS_UTF8
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Console drivers
 */
#define CONFIG_PC_KEYMAP 1
#undef  CONFIG_VGA_CONSOLE

/*
 * Frame-buffer support
 */
#define CONFIG_FB 1
#define CONFIG_DUMMY_CONSOLE 1
#undef  CONFIG_FB_ACORN
#undef  CONFIG_FB_ANAKIN
#undef  CONFIG_FB_CLPS711X
#undef  CONFIG_FB_S3C2410
#undef  CONFIG_FB_SA1100
#undef  CONFIG_FB_EPSON1356
#undef  CONFIG_FB_MQ200
#define CONFIG_FB_PXA 1
#undef  CONFIG_FB_PXA_8BPP
#define CONFIG_FB_PXA_16BPP 1
#define CONFIG_FB_MQ1100 1
#undef  CONFIG_FB_CYBER2000
#undef  CONFIG_FB_VIRTUAL
#define CONFIG_FBCON_ADVANCED 1
#undef  CONFIG_FBCON_MFB
#undef  CONFIG_FBCON_CFB2
#undef  CONFIG_FBCON_CFB4
#undef  CONFIG_FBCON_CFB8
#define CONFIG_FBCON_CFB16 1
#undef  CONFIG_FBCON_CFB24
#undef  CONFIG_FBCON_CFB32
#undef  CONFIG_FBCON_AFB
#undef  CONFIG_FBCON_ILBM
#undef  CONFIG_FBCON_IPLAN2P2
#undef  CONFIG_FBCON_IPLAN2P4
#undef  CONFIG_FBCON_IPLAN2P8
#undef  CONFIG_FBCON_MAC
#undef  CONFIG_FBCON_VGA_PLANES
#undef  CONFIG_FBCON_VGA
#undef  CONFIG_FBCON_HGA
#undef  CONFIG_FBCON_NO_LOGO
#undef  CONFIG_FBCON_FONTWIDTH8_ONLY
#define CONFIG_FBCON_FONTS 1
#define CONFIG_FONT_8x8 1
#undef  CONFIG_FONT_8x16
#undef  CONFIG_FONT_SUN8x16
#undef  CONFIG_FONT_SUN12x22
#undef  CONFIG_FONT_6x11
#undef  CONFIG_FONT_PEARL_8x8
#undef  CONFIG_FONT_ACORN_8x8

/*
 * Sound
 */
#define CONFIG_SOUND 1
#undef  CONFIG_SOUND_BT878
#undef  CONFIG_SOUND_CMPCI
#undef  CONFIG_SOUND_EMU10K1
#undef  CONFIG_MIDI_EMU10K1
#undef  CONFIG_SOUND_FUSION
#undef  CONFIG_SOUND_CS4281
#undef  CONFIG_SOUND_ES1370
#undef  CONFIG_SOUND_ES1371
#undef  CONFIG_SOUND_ESSSOLO1
#undef  CONFIG_SOUND_MAESTRO
#undef  CONFIG_SOUND_MAESTRO3
#undef  CONFIG_SOUND_ICH
#undef  CONFIG_SOUND_RME96XX
#undef  CONFIG_SOUND_SONICVIBES
#undef  CONFIG_SOUND_TRIDENT
#undef  CONFIG_SOUND_MSNDCLAS
#undef  CONFIG_SOUND_MSNDPIN
#undef  CONFIG_SOUND_VIA82CXXX
#undef  CONFIG_MIDI_VIA82CXXX
#undef  CONFIG_SOUND_H3900_UDA1380
#define CONFIG_SOUND_H3900_UDA1380_MODULE 1
#undef  CONFIG_SOUND_H5400
#define CONFIG_SOUND_H5400_MODULE 1
#undef  CONFIG_SOUND_OSS
#define CONFIG_SOUND_OSS_MODULE 1
#undef  CONFIG_SOUND_TRACEINIT
#undef  CONFIG_SOUND_DMAP
#undef  CONFIG_SOUND_AD1816
#undef  CONFIG_SOUND_SGALAXY
#undef  CONFIG_SOUND_ADLIB
#undef  CONFIG_SOUND_ACI_MIXER
#undef  CONFIG_SOUND_CS4232
#undef  CONFIG_SOUND_SSCAPE
#undef  CONFIG_SOUND_GUS
#undef  CONFIG_SOUND_VMIDI
#undef  CONFIG_SOUND_TRIX
#undef  CONFIG_SOUND_MSS
#undef  CONFIG_SOUND_MPU401
#undef  CONFIG_SOUND_NM256
#undef  CONFIG_SOUND_MAD16
#undef  CONFIG_SOUND_PAS
#undef  CONFIG_PAS_JOYSTICK
#undef  CONFIG_SOUND_PSS
#undef  CONFIG_SOUND_SB
#undef  CONFIG_SOUND_AWE32_SYNTH
#undef  CONFIG_SOUND_WAVEFRONT
#undef  CONFIG_SOUND_MAUI
#undef  CONFIG_SOUND_YM3812
#undef  CONFIG_SOUND_OPL3SA1
#undef  CONFIG_SOUND_OPL3SA2
#undef  CONFIG_SOUND_YMFPCI
#undef  CONFIG_SOUND_YMFPCI_LEGACY
#undef  CONFIG_SOUND_UART6850
#undef  CONFIG_SOUND_AEDSP16
#undef  CONFIG_SOUND_VIDC
#undef  CONFIG_SOUND_WAVEARTIST
#undef  CONFIG_SOUND_PXA_AC97
#define CONFIG_SOUND_PXA_AC97_MODULE 1
#undef  CONFIG_SOUND_TVMIXER

/*
 * Multimedia Capabilities Port drivers
 */
#undef  CONFIG_MCP
#undef  CONFIG_MCP_SA1100
#undef  CONFIG_MCP_UCB1200
#undef  CONFIG_MCP_UCB1200_AUDIO
#undef  CONFIG_MCP_UCB1200_TS
#undef  CONFIG_MCP_UCB1400_TS

/*
 * USB support
 */
#undef  CONFIG_USB
#define CONFIG_USB_MODULE 1
#undef  CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef  CONFIG_USB_BANDWIDTH
#undef  CONFIG_USB_LONG_TIMEOUT

/*
 * USB Host Controller Drivers
 */
#undef  CONFIG_USB_EHCI_HCD
#undef  CONFIG_USB_UHCI
#undef  CONFIG_USB_UHCI_ALT
#undef  CONFIG_USB_OHCI
#define CONFIG_USB_OHCI_MODULE 1
#undef  CONFIG_USB_OHCI_SA1111
#undef  CONFIG_USB_OHCI_H5400
#define CONFIG_USB_OHCI_H5400_MODULE 1
#undef  CONFIG_USB_OHCI_S3C2410
#undef  CONFIG_USB_SL811HS

/*
 * USB Device Class drivers
 */
#undef  CONFIG_USB_AUDIO
#define CONFIG_USB_AUDIO_MODULE 1
#undef  CONFIG_USB_EMI26
#undef  CONFIG_USB_BLUETOOTH
#undef  CONFIG_USB_STORAGE
#define CONFIG_USB_STORAGE_MODULE 1
#undef  CONFIG_USB_STORAGE_DEBUG
#undef  CONFIG_USB_STORAGE_DATAFAB
#undef  CONFIG_USB_STORAGE_FREECOM
#undef  CONFIG_USB_STORAGE_ISD200
#undef  CONFIG_USB_STORAGE_DPCM
#undef  CONFIG_USB_STORAGE_HP8200e
#undef  CONFIG_USB_STORAGE_SDDR09
#undef  CONFIG_USB_STORAGE_JUMPSHOT
#undef  CONFIG_USB_ACM
#undef  CONFIG_USB_PRINTER
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * USB Human Interface Devices (HID)
 */
#undef  CONFIG_USB_HID
#define CONFIG_USB_HID_MODULE 1
#define CONFIG_USB_HIDINPUT 1
#undef  CONFIG_USB_HIDDEV
#undef  CONFIG_USB_KBD
#undef  CONFIG_USB_MOUSE
#undef  CONFIG_USB_WACOM

/*
 * USB Imaging devices
 */
#undef  CONFIG_USB_DC2XX
#undef  CONFIG_USB_MDC800
#undef  CONFIG_USB_SCANNER
#undef  CONFIG_USB_MICROTEK
#undef  CONFIG_USB_HPUSBSCSI

/*
 * USB Multimedia devices
 */
#undef  CONFIG_USB_IBMCAM
#define CONFIG_USB_IBMCAM_MODULE 1
#undef  CONFIG_USB_OV511
#define CONFIG_USB_OV511_MODULE 1
#undef  CONFIG_USB_PWC
#define CONFIG_USB_PWC_MODULE 1
#undef  CONFIG_USB_SE401
#define CONFIG_USB_SE401_MODULE 1
#undef  CONFIG_USB_STV680
#define CONFIG_USB_STV680_MODULE 1
#undef  CONFIG_USB_VICAM
#define CONFIG_USB_VICAM_MODULE 1
#undef  CONFIG_USB_DSBR
#undef  CONFIG_USB_DABUSB

/*
 * USB Network adaptors
 */
#undef  CONFIG_USB_PEGASUS
#undef  CONFIG_USB_RTL8150
#undef  CONFIG_USB_KAWETH
#undef  CONFIG_USB_CATC
#undef  CONFIG_USB_CDCETHER
#define CONFIG_USB_CDCETHER_MODULE 1
#undef  CONFIG_USB_USBNET

/*
 * USB port drivers
 */
#undef  CONFIG_USB_USS720

/*
 * USB Serial Converter support
 */
#undef  CONFIG_USB_SERIAL
#undef  CONFIG_USB_SERIAL_GENERIC
#undef  CONFIG_USB_SERIAL_BELKIN
#undef  CONFIG_USB_SERIAL_WHITEHEAT
#undef  CONFIG_USB_SERIAL_DIGI_ACCELEPORT
#undef  CONFIG_USB_SERIAL_EMPEG
#undef  CONFIG_USB_SERIAL_FTDI_SIO
#undef  CONFIG_USB_SERIAL_VISOR
#undef  CONFIG_USB_SERIAL_IPAQ
#undef  CONFIG_USB_SERIAL_IR
#undef  CONFIG_USB_SERIAL_EDGEPORT
#undef  CONFIG_USB_SERIAL_KEYSPAN_PDA
#undef  CONFIG_USB_SERIAL_KEYSPAN
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA28
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA28X
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA28XA
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA28XB
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA19
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA18X
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA19W
#undef  CONFIG_USB_SERIAL_KEYSPAN_USA49W
#undef  CONFIG_USB_SERIAL_MCT_U232
#undef  CONFIG_USB_SERIAL_KLSI
#undef  CONFIG_USB_SERIAL_PL2303
#undef  CONFIG_USB_SERIAL_CYBERJACK
#undef  CONFIG_USB_SERIAL_XIRCOM
#undef  CONFIG_USB_SERIAL_OMNINET

/*
 * USB Miscellaneous drivers
 */
#undef  CONFIG_USB_RIO500
#undef  CONFIG_USB_AUERSWALD
#undef  CONFIG_USB_BRLVGER

/*
 * Linux As Bootldr Modules
 */
#undef  CONFIG_BIG_KERNEL
#undef  CONFIG_USE_DATE_CODE
#undef  CONFIG_YMODEM
#undef  CONFIG_LAB_DUMMY
#undef  CONFIG_LAB_CRC
#undef  CONFIG_LAB_YMODEM
#undef  CONFIG_LAB_MTD
#undef  CONFIG_LAB_COPY
#undef  CONFIG_LAB_COPY_YMODEM
#undef  CONFIG_LAB_COPY_FLASH
#undef  CONFIG_LAB_COPY_FS
#undef  CONFIG_LAB_COPY_WRAPPER

/*
 * Bluetooth support
 */
#undef  CONFIG_BLUEZ
#define CONFIG_BLUEZ_MODULE 1
#undef  CONFIG_BLUEZ_L2CAP
#define CONFIG_BLUEZ_L2CAP_MODULE 1
#undef  CONFIG_BLUEZ_SCO
#define CONFIG_BLUEZ_SCO_MODULE 1
#undef  CONFIG_BLUEZ_RFCOMM
#define CONFIG_BLUEZ_RFCOMM_MODULE 1
#define CONFIG_BLUEZ_RFCOMM_TTY 1
#undef  CONFIG_BLUEZ_BNEP
#define CONFIG_BLUEZ_BNEP_MODULE 1
#define CONFIG_BLUEZ_BNEP_MC_FILTER 1
#define CONFIG_BLUEZ_BNEP_PROTO_FILTER 1

/*
 * Bluetooth device drivers
 */
#undef  CONFIG_BLUEZ_HCIUSB
#undef  CONFIG_BLUEZ_HCIUART
#define CONFIG_BLUEZ_HCIUART_MODULE 1
#define CONFIG_BLUEZ_HCIUART_H4 1
#define CONFIG_BLUEZ_HCIUART_BCSP 1
#undef  CONFIG_BLUEZ_HCIUART_BCSP_TXCRC
#undef  CONFIG_BLUEZ_HCIDTL1
#define CONFIG_BLUEZ_HCIDTL1_MODULE 1
#undef  CONFIG_BLUEZ_HCIBT3C
#define CONFIG_BLUEZ_HCIBT3C_MODULE 1
#undef  CONFIG_BLUEZ_HCIBLUECARD
#define CONFIG_BLUEZ_HCIBLUECARD_MODULE 1
#undef  CONFIG_BLUEZ_HCIBTUART
#define CONFIG_BLUEZ_HCIBTUART_MODULE 1
#undef  CONFIG_BLUEZ_HCIVHCI

/*
 * Kernel hacking
 */
#define CONFIG_FRAME_POINTER 1
#undef  CONFIG_DEBUG_USER
#undef  CONFIG_DEBUG_INFO
#undef  CONFIG_NO_PGT_CACHE
#define CONFIG_DEBUG_KERNEL 1
#undef  CONFIG_DEBUG_SLAB
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_DEBUG_SPINLOCK
#undef  CONFIG_DEBUG_WAITQ
#undef  CONFIG_DEBUG_BUGVERBOSE
#define CONFIG_DEBUG_ERRORS 1
#undef  CONFIG_DEBUG_LL
#undef  CONFIG_DEBUG_DC21285_PORT
#undef  CONFIG_DEBUG_CLPS711X_UART2

/*
 * Library routines
 */
#undef  CONFIG_CRC32
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
