#define UTS_VERSION "#5 Fri Oct 31 10:19:59 EST 2003"
#define LINUX_COMPILE_TIME "10:19:59"
#define LINUX_COMPILE_BY "jamey"
#define LINUX_COMPILE_HOST "vimes.crl.hpl.hp.com"
#define LINUX_COMPILE_DOMAIN "crl.hpl.hp.com"
#define LINUX_COMPILER "gcc version 3.2.3"
